package com.example.authnz.bridge

/** Version of the bridge contract implemented here. Messages of any other version are ignored. */
const val BRIDGE_PROTOCOL_VERSION: Long = 1

/** Name of the object the native side injects into the page. Identical on every platform. */
const val BRIDGE_OBJECT_NAME: String = "NativeAuthBridge"

/** Failure reasons the native side may report for a token request. */
enum class BridgeErrorCode(val wireValue: String) {
    /** No credentials are stored; the page continues as a guest. */
    NOT_LOGGED_IN("not_logged_in"),

    /** Renewing the access token failed, for example because the refresh token was revoked. */
    REFRESH_FAILED("refresh_failed"),

    /** The person dismissed the local authentication prompt. */
    USER_CANCELLED("user_cancelled"),

    /** Local authentication is required but cannot be presented right now. */
    LOCKED("locked"),

    /** Anything else. The optional message is for diagnostics only. */
    INTERNAL_ERROR("internal_error"),
}

/** A request sent by the page. */
sealed interface BridgeRequest {

    /** Correlates the reply with the request. Generated by the page. */
    val requestId: String

    /** Asks for an access token. */
    data class GetToken(
        override val requestId: String,
        val forceRefresh: Boolean,
    ) : BridgeRequest
}

/**
 * Reads the requests the page sends and builds the replies the native side sends back.
 *
 * Reading is deliberately strict: anything the contract does not describe - a malformed document,
 * an unknown version, an unknown type, a missing or empty request id, a field of the wrong type -
 * yields `null` so that the caller stays silent instead of answering.
 */
object BridgeMessages {

    private const val FIELD_VERSION = "version"
    private const val FIELD_TYPE = "type"
    private const val FIELD_REQUEST_ID = "requestId"
    private const val FIELD_FORCE_REFRESH = "forceRefresh"
    private const val FIELD_ACCESS_TOKEN = "accessToken"
    private const val FIELD_EXPIRES_AT = "expiresAt"
    private const val FIELD_CODE = "code"
    private const val FIELD_MESSAGE = "message"

    private const val TYPE_GET_TOKEN = "getToken"
    private const val TYPE_TOKEN_RESULT = "tokenResult"
    private const val TYPE_ERROR = "error"
    private const val TYPE_LOGOUT = "logout"

    /** Returns the request carried by [payload], or `null` when it must be ignored. */
    fun parseRequest(payload: String): BridgeRequest? {
        val members = MiniJson.parseObject(payload) ?: return null
        if (versionOf(members) != BRIDGE_PROTOCOL_VERSION) return null
        return when (members[FIELD_TYPE]) {
            TYPE_GET_TOKEN -> parseGetToken(members)
            else -> null
        }
    }

    /**
     * The version as a whole number. JavaScript has a single number type, so `1` may arrive either
     * as an integer or as `1.0`; both mean version 1, and anything else means "not this version".
     */
    private fun versionOf(members: Map<String, Any?>): Long? = when (val raw = members[FIELD_VERSION]) {
        is Long -> raw
        is Double -> if (raw % 1.0 == 0.0) raw.toLong() else null
        else -> null
    }

    private fun parseGetToken(members: Map<String, Any?>): BridgeRequest? {
        val requestId = members[FIELD_REQUEST_ID] as? String ?: return null
        if (requestId.isEmpty()) return null
        val forceRefresh = when (val raw = members[FIELD_FORCE_REFRESH]) {
            null -> false
            is Boolean -> raw
            else -> return null
        }
        return BridgeRequest.GetToken(requestId, forceRefresh)
    }

    /** Successful reply to a `getToken` request. */
    fun tokenResult(requestId: String, accessToken: String, expiresAtEpochMillis: Long): String =
        MiniJson.writeObject(
            listOf(
                FIELD_VERSION to BRIDGE_PROTOCOL_VERSION,
                FIELD_TYPE to TYPE_TOKEN_RESULT,
                FIELD_REQUEST_ID to requestId,
                FIELD_ACCESS_TOKEN to accessToken,
                FIELD_EXPIRES_AT to expiresAtEpochMillis,
            ),
        )

    /** Failed reply to a `getToken` request. [message] is diagnostic and never shown to the user. */
    fun error(requestId: String, code: BridgeErrorCode, message: String? = null): String {
        val members = mutableListOf<Pair<String, Any?>>(
            FIELD_VERSION to BRIDGE_PROTOCOL_VERSION,
            FIELD_TYPE to TYPE_ERROR,
            FIELD_REQUEST_ID to requestId,
            FIELD_CODE to code.wireValue,
        )
        if (message != null) members.add(FIELD_MESSAGE to message)
        return MiniJson.writeObject(members)
    }

    /** Unsolicited notification that the native side signed out. Carries no request id. */
    fun logout(): String =
        MiniJson.writeObject(
            listOf(
                FIELD_VERSION to BRIDGE_PROTOCOL_VERSION,
                FIELD_TYPE to TYPE_LOGOUT,
            ),
        )
}
